CREATE BIGFILE TABLESPACE &&1 DATAFILE 
  '+DATA01' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
NOLOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 32K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE USER &&1
  IDENTIFIED BY &2
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE &&1
  TEMPORARY TABLESPACE TEMP
  PROFILE USER_TECH
  ACCOUNT UNLOCK;

-- 2 Roles 
GRANT CONNECT TO &&1;
GRANT RESOURCE TO &&1;
ALTER USER &&1 DEFAULT ROLE ALL;

-- 1 System Privilege 
GRANT CREATE VIEW TO &&1;

-- 1 Tablespace Quota f
ALTER USER &&1 QUOTA UNLIMITED ON &&1;

