grant REDEFINE ANY TABLE  to dwh_foundation;
grant ADMINISTER DATABASE TRIGGER to dwh_foundation;
grant ALTER ANY INDEX to dwh_foundation; 
grant ALTER ANY MATERIALIZED VIEW to dwh_foundation;
grant ALTER ANY SEQUENCE to dwh_foundation;
grant ALTER ANY TRIGGER to dwh_foundation;
grant CREATE ANY INDEX to dwh_foundation;
grant CREATE ANY MATERIALIZED VIEW to dwh_foundation;
grant CREATE ANY SEQUENCE to dwh_foundation;
grant CREATE ANY TABLE to dwh_foundation;
grant CREATE ANY TRIGGER to dwh_foundation;
grant CREATE ANY VIEW to dwh_foundation;
grant CREATE MATERIALIZED VIEW to dwh_foundation;
grant CREATE SESSION to dwh_foundation;
grant CREATE VIEW to dwh_foundation;
grant DROP ANY INDEX to dwh_foundation;
grant DROP ANY MATERIALIZED VIEW to dwh_foundation;
grant DROP ANY SEQUENCE to dwh_foundation;
grant DROP ANY TRIGGER to dwh_foundation;
grant DROP ANY VIEW to dwh_foundation;
grant EXECUTE ANY PROCEDURE to dwh_foundation;
grant INSERT ANY TABLE to dwh_foundation;
grant MERGE ANY VIEW to dwh_foundation;
grant SELECT ANY DICTIONARY to dwh_foundation;
grant SELECT ANY TABLE to dwh_foundation;
grant UNDER ANY VIEW to dwh_foundation;
grant UPDATE ANY TABLE to dwh_foundation;

grant execute on dbms_redefinition to dwh_foundation;
grant ALTER ANY TABLE  to dwh_foundation;
grant CREATE ANY TABLE to dwh_foundation;
grant DROP ANY TABLE to dwh_foundation;
grant LOCK ANY TABLE to dwh_foundation;
grant SELECT ANY TABLE to dwh_foundation;
grant CREATE ANY TRIGGER to dwh_foundation;
grant CREATE ANY INDEX to dwh_foundation;