SELECT  
 DTM_CF_FINANCIALMARKET.DTM_TRADEOPE_REG_DLY_BE_seq.NEXTVAL MESSAGE_REF,
 OP.*
FROM
(
SELECT DISTINCT
 o.OP_CLEREGR,
 o.OP_NUMBER,
 o.OP_PSO_CODE,
 o.OP_STATUT_TITRE_CODE,
 o.OP_INDICE_CLIEN_CTPT_CODE,
 o.OP_OPER_CURRENCY,
 o.OP_EMISS_CURRENCY,
 o.OP_SECURITY_QUANTITY,
 o.OP_SECURITY_PRICE,
 o.OP_SECURITY_RATE,
 o.OP_AMOUNT_VALO,
 TRIM (o.OP_VALUE_DATE) OP_VALO_DATE,
 TRIM (o.OP_TITRE_SETTLEMENT_DATE) OP_SETL_DATE,
 TRIM (o.OP_ENCODING_DATE) OP_ENCOD_DATE,
 TRIM (o.OP_START_DATE) OP_START_DATE,
 TRIM (o.OP_END_DATE) OP_END_DATE,
 TRIM (o.OP_EXECUTION_DATE) OP_EXEC_DATE,
 vi.INS_NOVALSYS,
 vi.INS_KEY_GTDATA,
 vi.INS_LABEL1_EN,
 vi.INS_ISIN_SOUS_JACENT,
 to_char(vi.INS_D_LIMIT_EXER,'YYYYMMDD') as INS_D_LIMIT_EXER,
 vi.INS_OPTION_SENS_LIB,
 vi.INS_OPTION_STYLE_CODE,
 vi.INS_STRIKE,
 vi.INS_EMIS_CURR_ISO_CODE,
 vi.INS_CRS_VALORISATION,
 a.ACCOUNT_NUMBER,
 TRIM (a.ACCOUNT_ROOT_NUMBER) ACCOUNT_ROOT_NUMBER,
 a.ACCOUNT_KEY_PARTY,
 p.PERSON_REF,
 p.PERSON_KEY_PARTY,
 p.PERSON_NATIONALITY_SIGLE,
 TRIM (p.PERSON_IDENT_LEI) PERSON_IDENT_LEI,
 TRIM (p.PERSON_TYPE_SIGLE) PERSON_TYPE_SIGLE,
 p.PERSON_ADRLAW_COUNTRY_ISO,
 p.PERSON_EMIR_FLAG PERSON_DELEGATION_EMIR,
 a.ACCOUNT_ROOT_ECO_SECT_CODE,
 a.ACCOUNT_ROOT_TYPE_SIGLE,
 vi.INS_CATEGORY_CODE,
 vi.INS_CATEGORY_LIB,
 vi.INS_SUBCATEGORY_CODE,
 vi.INS_CLASSIFIC_CFI_CODE,
 TRIM (o.OP_INSTRUCTION1) OP_INSTRUCTION1,
 TRIM (REPLACE (REPLACE (REPLACE (REPLACE (o.OP_INSTRUCTION2, '.', ''), '@', ''), '_', ''), '-', '')) OP_INSTRUCTION2,
 TRIM (o.OP_INSTRUCTION3) OP_INSTRUCTION3
FROM DTM_CF_TRANSACTIONAL.OPER_AVSR o
INNER JOIN DTM_CF_REFERENTIAL.VW_INS_INSTRUMENT vi ON ( vi.INS_NOVALSYS = o.OP_INSTRUMENT_NOVAL AND  vi.INS_COUNTRY = 'BE' AND vi.INS_COMPTA_TYPE_CODE = '1')
LEFT OUTER JOIN  DTM_CF_REFERENTIAL.CIS_ACCOUNT a ON
 (o.OP_ACCOUNT_TITRE_SK = a.ACCOUNT_SK
 AND a.ACCOUNT_COUNTRY = 'BE'
 AND a.ACCOUNT_KIND = 'T'
 AND a.ACCOUNT_FLAG_ACTIVE = 'Y'
 )
INNER JOIN  DTM_CF_REFERENTIAL.CIS_PERSON p ON ( a.ACCOUNT_PERSON_REF = p.PERSON_REF  AND p.PERSON_ENTITY = 'BDPB')
WHERE
o.OP_ENCODING_DATE >= 20190101 and o.OP_ENCODING_DATE < 20200101
AND o.OP_PSO_CODE = '0860'
AND  o.OP_INDICE_CLIEN_CTPT_CODE = '0001'
AND ( vi.INS_LABEL1_EN LIKE '%SOURCE%' OR vi.INS_LABEL1_EN LIKE '%DB%')
AND  a.ACCOUNT_NATURE_CODE = '0170'
AND UPPER(vi.INS_CATEGORY_LIB) = 'OPTION'
AND o.OP_STATUT_TITRE_CODE IN ('0065', '0075')
AND  SUBSTR (o.OP_INSTRUCTION3, 9, 1) = 'S'
ORDER BY
 o.OP_CLEREGR
) OP ;
